export const ListData = [
  { index: 1, value: "learn react", done: true },
  { index: 2, value: "Revise Literature review", done: false },
  { index: 3, value: "Send mail", done: false },
  { index: 4, value: "learn react", done: true },
  { index: 5, value: "Revise Literature review", done: false },
  { index: 6, value: "learn react", done: true },
  { index: 7, value: "Revise Literature review", done: false },
  { index: 8, value: "Send mail", done: false },
  { index: 9, value: "learn react", done: true },
  { index: 10, value: "Revise Literature review", done: false },
  { index: 11, value: "learn react", done: true },
  { index: 12, value: "learn react", done: true },
  { index: 13, value: "learn react", done: true },
  { index: 14, value: "learn react", done: true },
  { index: 15, value: "learn react", done: true },
  { index: 16, value: "learn react", done: true },
  { index: 17, value: "learn react", done: true },
  { index: 18, value: "learn react", done: true },
  { index: 19, value: "learn react", done: true },
  { index: 20, value: "learn react", done: true },
  { index: 21, value: "learn react", done: true },
  { index: 22, value: "learn react", done: true },
  { index: 23, value: "learn react", done: true },
  { index: 24, value: "learn react", done: true },
  { index: 25, value: "learn react", done: true },
  { index: 26, value: "learn react", done: true },
  { index: 27, value: "learn react", done: true },
  { index: 28, value: "learn react", done: true },
  { index: 29, value: "learn react", done: true },
  { index: 30, value: "learn react", done: true },
  { index: 31, value: "learn react", done: true },
  { index: 32, value: "learn react", done: true },
  { index: 33, value: "learn react", done: true },
  { index: 34, value: "learn react", done: true },
];
